### ISSUE TITLE
Software Engineering: Webcam Port Forwarding Access Denied

### ISSUE THREAD

**Issue by ds7-ds** [ds7-ds/Model-Airport#40]
The project is finally done however webcam access to the internet has been denied by the router's administrator. The administrator believes port forwarding is dangerous because it reveals the general location of the router to users which is true. But without the webcam, the user cannot experience the model airport app to the fullest online anywhere in the world. The app can currently be used when around the model airport due to the restriction. Other alternatives must be taken to go around this issue until if port forwarding access has been granted.

**Comment by ds7-ds** [comment]
Options that are available:
* Skype
* Data network/Mobile Hotspot?
* Proxy server in LAN network

**Comment by ds7-ds** [comment]
* Skype is available on the Windows Phone and the Meet Now feature does allow browser meetings however this may not work for this project
* Data network is not possible because the phone has been dropped from that feature and plus it's expensive. Same goes for mobile hotspot.
* Proxy server seems possible and worthwhile to explore

**Comment by ds7-ds** [comment]
Pursuing proxy server for webcam. The webcam uses an MJPEG stream format on browsers and apps. This format uses *multipart/x-mixed-replace;boundary=<boundary-name>* mime content type when transferring over HTTP. This means that when the browser receives this header, it will keep itself open to new content until the stream ends. Trying to figure out how to pass the MJPEG stream to the proxy server so that it can pass it onto the user's browser. Currently toying around with node-mjpeg-proxy in npm repository.

**Comment by ds7-ds** [comment]
The documentation and examples for the node-mjpeg-proxy code are not clear and did not work for the webcam. There's no alternative to this and not much time to create my own. This solution would have exposed the webcam only to the server and not to clients. It would have also relaxed the fears of the administrator. However, it can't be done. There may be a possibility to decode the mjpeg stream, extract the jpeg and send it to the proxy server. There is a mjpeg-decoder repo on npm to try out.

**Comment by ds7-ds** [comment]
The mjpeg-decoder works however because of the CORS policy (localhost and MJPEG url are different), the code halts and errors are given on the console. The decoder uses the fetch function which works if the url is on the same domain as that of the served webpage.

**Comment by ds7-ds** [comment]
Tried using [html2canvas](https://html2canvas.hertzen.com/) to take a snapshot of the iframe however this library reads the DOM and replicates it which can then be converted to an image. The documentation was not clear on how it worked until a StackOverflow post cleared the doubt.

**Comment by ds7-ds** [comment]
Dropped html2canvas library idea. Browser was being used to visualize the problem better. This idea will not work in node.js but well worth the try. Good to know such thing exists. After tinkering with the code, the problem was how the stream was embedded. Replaced the iFrame with Img tag. This removes unneccesary overhead caused by iFrame.

**Comment by DarshanShet777** [comment]
The img tag solved part of the problem however it introduced new problems which was CORS again. Canvas was used to copy the image and then convert to base64 format. That string would then be sent to the proxy server to be sent to clients. However, it proved to be rough and dirty solution. Before this solution was completed, it was understandable that the code used would have slowed down the server and the client's device. Best to convince the administrator again and explain all attempts to try other solutions proved fruitless

**Comment by ds7-ds** [comment]
No chance of convincing. Will have to work with what is available if not best. The JPEG compression is an issue because normal file size is 300kb with compression of 150kb with lz-string.

**Comment by ds7-ds** [comment]
Many of the strange solutions have been tried due to CORS issue. That's why dealing with HTTP servers were avoided. However, the solution of using a proxy server needs one more thing: another proxy server. The new solution comes from reading this [stackoverflow post](https://stackoverflow.com/questions/40305130/nodejs-request-proxy-streammjpeg-connection-never-ends). This would require the webcam to connect to a device on the local network with server capabilities such as a laptop,desktop, or even the RPi itself (depending on CPU ability). The local server would then connect to a Heroku server to transfer the mjpeg stream to the user. All of this transferring will be done using the pipe function as explained [here](https://www.freecodecamp.org/news/node-js-streams-everything-you-need-to-know-c9141306be93/).

**Comment by ds7-ds** [comment]
This current solution has its own problems and must be opened in a new issue.
